# Generated by Django 4.2.18 on 2025-02-01 08:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", ckeditor.fields.RichTextField()),
                ("language_code", models.CharField(default="en", max_length=10)),
                ("translations", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
