# Generated by Django 4.2.18 on 2025-02-02 12:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="language_code",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="translations",
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_bn",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Bengali Answer"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Hindi Answer"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_bn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bengali Question"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hindi Question"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(verbose_name="Question"),
        ),
    ]
