# Generated by Django 4.2.18 on 2025-02-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_remove_faq_language_code_remove_faq_translations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_bn",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_bn",
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_hi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_hi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
