# Generated by Django 4.2.18 on 2025-02-02 12:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0003_remove_faq_answer_bn_remove_faq_question_bn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
