# Generated by Django 4.2.18 on 2025-02-02 14:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0004_alter_faq_answer_alter_faq_answer_hi"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_bn",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_bn",
            field=models.TextField(blank=True, null=True),
        ),
    ]
